# Generated by Django 2.0 on 2018-03-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_change', models.CharField(max_length=500, verbose_name='接口变更说明')),
                ('api_send_status', models.BooleanField(default=True, verbose_name='是否下发')),
                ('change_time', models.DateTimeField(verbose_name='接口变更时间')),
            ],
        ),
        migrations.CreateModel(
            name='ApiMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='接口名称')),
                ('url_name', models.CharField(max_length=250, verbose_name='路由信息')),
                ('request_name', models.CharField(max_length=10, verbose_name='请求方式')),
                ('component_owner', models.CharField(max_length=250, verbose_name='从属服务')),
                ('api_status', models.BooleanField(default=True, verbose_name='是否在用')),
            ],
        ),
        migrations.CreateModel(
            name='ApiRelationMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_component_name', models.CharField(max_length=250, verbose_name='调用接口的组件名称')),
                ('re_component_director', models.IntegerField(verbose_name='负责人联系方式')),
                ('use_message', models.CharField(blank=True, max_length=500, null=True, verbose_name='调用说明')),
                ('api_message', models.ManyToManyField(to='learn.ApiMessage')),
            ],
        ),
        migrations.AddField(
            model_name='apichangelog',
            name='api_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.ApiMessage'),
        ),
    ]
