# Generated by Django 2.0 on 2018-02-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_apimessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimessage',
            name='api_call',
        ),
        migrations.AlterField(
            model_name='apimessage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='接口名称'),
        ),
    ]
