# Generated by Django 2.0 on 2018-02-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180202_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimessage',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='接口名称'),
        ),
    ]
